[theme]
primaryColor = "#00ADB5"       # Ciano (Destaque para bot√µes e sliders)
backgroundColor = "#1E2130"    # Fundo Principal (Azul Profundo Suave)
secondaryBackgroundColor = "#262A3B" # Sidebar e fundos de input
textColor = "#E0E6ED"          # Texto Principal (Branco Gelo)
font = "sans serif"